orbs:
  aws-ecr: circleci/aws-ecr@6.9.1
  aws-ecs: circleci/aws-ecs@1.0.5
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: my_aws
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./testproject
          profile-name: circleci
          region: AWS_REGION_ENV_VAR_NAME
          repo: mytestcicd
          tag: '${CIRCLE_SHA1}'
     - aws-ecs/update-task-definition-from-json:
              task-definition-json: my-app-definition.json
