orbs:
  aws-ecr: circleci/aws-ecr@6.9.1
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      -build_and_push_image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: my_aws
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./testproject
          profile-name: circleci
          region: AWS_REGION_ENV_VAR_NAME
          repo: mytestcicd
          tag: 'latest,myECRRepoTag'
